### PR TITLE
fix: avoid setting ssl_certificate and remove it from tests

### LINKED ISSUE #193: bug: Deprecated `ssl_certificates` never reconciles when removed
### Terraform version

1.2.9

### Provider version

1.6.2

### Steps to reproduce

Define a `checkly_check_group`, providing `alert_settings`.

### What is expected?

`ssl_certificates` is deprecated, so I shouldn't need to provide it.

```hcl
  alert_settings {
    escalation_type = "RUN_BASED"

    time_based_escalation {
      minutes_failing_threshold = 5
    }

    run_based_escalation {
      failed_run_threshold = 1
    }

    reminders {
      amount   = 5
      interval = 15
    }
  }
```

### What is actually happening?

`ssl_certificates` always wants to be defined, even if the values are basically noops:

```
# module.xxxxxxxxx.checkly_check_group.xxxxxxxxxx will be updated in-place
  ~ resource "checkly_check_group" "xxxxxxxxxx" {
        id                        = "xxxxxxxxx"
        name                      = "xxxxxxx"
        tags                      = [
            "xxxxxxx",
        ]
        # (10 unchanged attributes hidden)

      - alert_settings {
          - escalation_type = "TIME_BASED" -> null

          - reminders {
              - amount   = 5 -> null
              - interval = 15 -> null
            }

          - run_based_escalation {
              - failed_run_threshold = 1 -> null
            }

          - ssl_certificates {
              - alert_threshold = 0 -> null
              - enabled         = false -> null
            }

          - time_based_escalation {
              - minutes_failing_threshold = 5 -> null
            }
        }
      + alert_settings {
          + escalation_type = "TIME_BASED"

          + reminders {
              + amount   = 5
              + interval = 15
            }

          + run_based_escalation {
              + failed_run_threshold = 1
            }

          + time_based_escalation {
              + minutes_failing_threshold = 5
            }
        }

        # (3 unchanged blocks hidden)
    }

```

Notice the `ssl_certificates` block is being removed, but even after applying successfully still wants to be removed.

### System Info

_No response_

### Any additional comments?

For now, I can keep `ssl_certificates` defined, and just live with the warnings, but that's obviously not ideal.

### PR DESCRIPTION
**Pull request by ianaya89**
## Affected Components
* [x] Resources
* [ ] Test
* [ ] Docs
* [ ] Tooling
* [ ] Other

## Pre-Requisites
* [x] Terraform code is formatted with `terraform fmt`
* [x] Go code is formatted with `go fmt`
* [x] `plan` & `apply` command of `demo/main.tf` file do not produce diffs

## Notes for the Reviewer
- Avoid setting/getting `ssl_certificates` property
- Remove it from docs and fixtures

> Resolves #193

### CODE REVIEW

File: checkly/resource_check.go [hunk 1]
```diff
@@ -280,13 +280,12 @@ func resourceCheck() *schema.Resource {
 						"ssl_certificates": {
 							Type:       schema.TypeSet,
 							Optional:   true,
-							Deprecated: "The property `ssl_certificates` is deprecated and it's ignored by the Checkly Public API. It will be removed in a future version.",
+							Deprecated: "This property is deprecated and it's ignored by the Checkly Public API. It will be removed in a future version.",
```
Comment (RealOrangeOne) [inline checkly/resource_check.go:283]: This change sadly makes it ambiguous which argument has been deprecated. Really Terraform should be dealing with this nicer, so I've raised an issue upstream: https://github.com/hashicorp/terraform-plugin-sdk/issues/1094

Comment (ianaya89) [reply checkly/resource_check.go:283]: @RealOrangeOne thanks for the feedback, do you think we can make something for now to improve the DX and make it clear?

Comment (ianaya89) [reply checkly/resource_check.go:283]: I guess the original message was better than the new one for user understanding
